sonar.projectKey=dogu-lib

sonar.sources=.
sonar.exclusions=**/testutil/**,**/mocks/**,**/*_mock.go,**/vendor/**,**/target/**,**/zz_generated.deepcopy.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**,**/target/**

sonar.junit.reportPaths=target/unit-tests/unit-tests.xml
sonar.go.coverage.reportPaths=target/unit-tests/coverage.out
sonar.go.golangci-lint.reportPaths=target/static-analysis/static-analysis-cs.log
